name:                BeepBoop
version:             0.1.0.0
github:              "ners/BeepBoop"
license:             BSD3
author:              "ners"
maintainer:          "ners@gmx.ch"
copyright:           "2020 ners"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ners/BeepBoop#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- flac
- wave

executables:
  BeepBoop-exe:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
